stages:
  - build

default:
  tags:
    - thehivehook_go
#  before_script:
#    - echo "URL repository: ${CI_REPOSITORY_URL}"  

build-job:
  stage: build
  only:
    refs:
      - master
      - latest
  before_script:
    - echo "Execute this `before_script` in all jobs by default."
  script: 
    - pwd
    - docker-compose -f $CI_PROJECT_DIR/docker-compose.yml down 
    - docker rmi ${CI_REPOSITORY_URL}
    - docker-compose -f $CI_PROJECT_DIR/docker-compose.yml up -d --force-recreate --build