stages:
  - build

before-script:
  script:
    - echo 'URL repository: ${CI_REPOSITORY_URL}'

default:
  tags:
    - thehivehook_go

build-job:
  stage: build
  only:
    refs:
      - master
      - latest
  script: 
    - pwd
    - docker-compose -f $CI_PROJECT_DIR/docker-compose.yml down 
    - docker rmi ${CI_REPOSITORY_URL}
    - docker-compose -f $CI_PROJECT_DIR/docker-compose.yml up -d --force-recreate --build