stages:
  - build

default:
  tags:
    - thehivehook_go

build-job:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - README.md
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: on_success
  before_script:
    - echo "Current URL repository - $CI_REPOSITORY_URL"
  script: 
    - pwd
    - docker-compose -f $CI_PROJECT_DIR/docker-compose.yml down 
    - docker rmi gitlab.cloud.gcm:5050/a.belyakov/thehivehook_go_package
    - docker-compose -f $CI_PROJECT_DIR/docker-compose.yml up -d --force-recreate --build